import axios, { type AxiosInstance } from 'axios';
import type { ITeamsAdapter } from '../interfaces/index.js';

/**
 * Microsoft Teams adapter implementation using Graph API
 */
export class TeamsAdapter implements ITeamsAdapter {
  private readonly client: AxiosInstance;

  constructor(config: { accessToken: string }) {
    this.client = axios.create({
      baseURL: 'https://graph.microsoft.com/v1.0',
      headers: {
        Authorization: `Bearer ${config.accessToken}`,
        'Content-Type': 'application/json',
      },
    });
  }

  async sendChannelMessage(params: {
    teamId: string;
    channelId: string;
    message: string;
    format?: 'text' | 'markdown';
    importance?: 'normal' | 'high' | 'urgent';
  }): Promise<void> {
    const body = {
      body: {
        contentType: params.format === 'markdown' ? 'html' : 'text',
        content: params.message,
      },
      importance: params.importance ?? 'normal',
    };

    await this.client.post(
      `/teams/${params.teamId}/channels/${params.channelId}/messages`,
      body
    );
  }

  async sendPRNotification(params: {
    teamId: string;
    channelId: string;
    prUrl: string;
    prTitle: string;
    repository: string;
    bugTitle: string;
    workItemId?: number;
    fixSummary: string;
  }): Promise<void> {
    const message = this.formatPRNotification(params);
    await this.sendChannelMessage({
      teamId: params.teamId,
      channelId: params.channelId,
      message,
      format: 'markdown',
      importance: 'high',
    });
  }

  async sendErrorNotification(params: {
    teamId: string;
    channelId: string;
    errorMessage: string;
    errorId: string;
    stage: string;
  }): Promise<void> {
    const message = `
⚠️ **Auto-Fix Error**

**Error ID:** ${params.errorId}
**Stage:** ${params.stage}
**Message:** ${params.errorMessage}

The automated bug fix process encountered an error. Manual intervention may be required.
    `.trim();

    await this.sendChannelMessage({
      teamId: params.teamId,
      channelId: params.channelId,
      message,
      format: 'markdown',
      importance: 'urgent',
    });
  }

  async listTeams(): Promise<
    Array<{ id: string; displayName: string; description?: string }>
  > {
    const response = await this.client.get('/me/joinedTeams');
    const teams = response.data.value as Array<{
      id: string;
      displayName: string;
      description?: string;
    }>;

    return teams.map((team) => ({
      id: team.id,
      displayName: team.displayName,
      description: team.description,
    }));
  }

  async listChannels(
    teamId: string
  ): Promise<Array<{ id: string; displayName: string; description?: string }>> {
    const response = await this.client.get(`/teams/${teamId}/channels`);
    const channels = response.data.value as Array<{
      id: string;
      displayName: string;
      description?: string;
    }>;

    return channels.map((channel) => ({
      id: channel.id,
      displayName: channel.displayName,
      description: channel.description,
    }));
  }

  private formatPRNotification(params: {
    prUrl: string;
    prTitle: string;
    repository: string;
    bugTitle: string;
    workItemId?: number;
    fixSummary: string;
  }): string {
    const workItemLink = params.workItemId
      ? `\n**Work Item:** #${params.workItemId}`
      : '';

    return `
🤖 **Automated Bug Fix PR Created**

**Repository:** ${params.repository}
**Bug:** ${params.bugTitle}${workItemLink}

**Summary:** ${params.fixSummary}

[**View Pull Request →**](${params.prUrl})

---
_This PR was automatically generated by the error monitor system using Warp Oz._
    `.trim();
  }
}
